version: "3.7"

services:
  postgres:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_accounts
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: r9Y7VaBwDM7a
      POSTGRES_PORT: 5432
      POSTGRES_DB: yats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
